name: CI - MLflow Project + Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_train:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/workflow-ci-image
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:latest ./Workflow-CI/MLProject
    
    - name: Test Docker image
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/Workflow-CI/MLProject:/app \
          $IMAGE_NAME:latest \
          python -c "import pandas, numpy, sklearn, mlflow; print('All imports successful')"
    
    - name: Run MLflow training
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/Workflow-CI/MLProject:/app \
          -w /app \
          $IMAGE_NAME:latest \
          mlflow run . --experiment-name spam_classification --env-manager=local
    
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
<<<<<<< HEAD
        docker push $IMAGE_NAME:latest
=======
        docker push $IMAGE_NAME:latest
>>>>>>> de6a21608565b623d3ec16e87571868afcae52ce
