name: CI - MLflow Project + Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build_and_train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t XzyanQi/workflow-ci-image:latest ./Workflow-CI/MLProject
        docker push XzyanQi/workflow-ci-image:latest

    - name: Run MLflow training inside Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/Workflow-CI/MLProject \
          XzyanQi/workflow-ci-image:latest \
          mlflow run . --experiment-name "spam_classification" --env-manager=local
